# Generated by Django 4.1.3 on 2022-12-22 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_country_alter_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=50)),
                ("unit_number", models.IntegerField(default=0)),
                (
                    "country_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.country",
                    ),
                ),
            ],
        ),
    ]
