# Generated by Django 4.1.3 on 2022-12-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_order_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
