# Generated by Django 4.1.3 on 2022-12-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_alter_order_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer_Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rating_value", models.IntegerField()),
                ("comment", models.CharField(max_length=255)),
                (
                    "customer_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.customer",
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.order",
                    ),
                ),
            ],
        ),
    ]
