# Generated by Django 4.1.3 on 2022-12-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_customer_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tel_Number",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("number", models.IntegerField(default=0)),
                (
                    "customer_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.customer",
                    ),
                ),
            ],
        ),
    ]
