# Generated by Django 4.1.3 on 2022-12-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_tel_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shopping_Cart",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "customer_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.customer",
                    ),
                ),
            ],
        ),
    ]
