# Generated by Django 4.1.3 on 2022-12-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0022_shoping_cart_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("account_number", models.CharField(max_length=50)),
                ("expiry_date", models.CharField(max_length=50)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "customer_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.customer",
                    ),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.order",
                    ),
                ),
            ],
        ),
    ]
